### ISSUE TITLE
NullPointerException in TileEntityGemCutter.refine

### ISSUE THREAD

**Issue by amcoder** [jaredlll08/Fluxed-Crystals#55]
I've been getting a crash using the Gem cutter. I'm on 0.0.5i, but this also happened in previous versions.

```
[00:35:35] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel fluxedcrystals
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[guava-16.0.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:40) ~[guava-16.0.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:89) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:86) ~[FMLOutboundHandler$OutboundTarget$3.class:?]
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToDimension(SimpleNetworkWrapper.java:224) ~[SimpleNetworkWrapper.class:?]
	at fluxedCrystals.tileEntity.TileEntityGemCutter.refine(TileEntityGemCutter.java:339) ~[TileEntityGemCutter.class:?]
	at fluxedCrystals.tileEntity.TileEntityGemCutter.func_145845_h(TileEntityGemCutter.java:93) ~[TileEntityGemCutter.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1995) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) ~[1.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]
```

**Comment by amcoder** [comment]
After some more testing, it seems like this happens when I set up a new gem cutter. After I apply power and it processes a few shards, the game crashes with this exception. I log back in, restart the cutter, and it seems to run fine after that.

If I break the block and set it up again, I get the crash.

**Comment by jaredlll08** [comment]
Thanks, Thought I fixed this :)
